version: '3.8'
services:
  config-server:
    image: config-server-image:1.0
    ports:
      - 8081:8081
    environment:
      - SPRING_APPLICATION_NAME=config-server
      - SERVER_PORT=8081
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL=master
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/Martinodark19/microservicios-deploy.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=config-data
    networks:
      - microservices-network

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://config-server:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  eureka-server:
    image: eureka-server-image:1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
      - SPRING_CLOUD_CONFIG_ENABLED=true
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8081
     
    networks:
      - microservices-network

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://eureka-server:8761/actuator/health || exit 1"]
      interval: 30s    
      timeout: 30s
      retries: 5
      start_period: 30s

    depends_on:
       config-server:
          condition: service_healthy

  gateway-service:
    image: gateway-service-image:1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8081
      - SPRING_CLOUD_CONFIG_ENABLED=true
    networks:
      - microservices-network

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://gateway-service:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

    depends_on:
       config-server:
          condition: service_healthy
       eureka-server:
          condition: service_healthy

  usuario-service:
    image: usuario-service-image:1.0
    ports:
      - 9090:9090
    environment:
      - SPRING_APPLICATION_NAME=usuario-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8081
      - SPRING_CLOUD_CONFIG_ENABLED=true

    networks:
      - microservices-network
    depends_on:
       config-server:
          condition: service_healthy
       eureka-server:
          condition: service_healthy
       gateway-service:
          condition: service_healthy

  moto-service:
    image: moto-service-image:1.0
    ports:
      - 9000:9000 
    environment:
      - SPRING_APPLICATION_NAME=moto-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8081
      - SPRING_CLOUD_CONFIG_ENABLED=true
    networks:
      - microservices-network

    depends_on:
       config-server:
          condition: service_healthy
       eureka-server:
          condition: service_healthy
       gateway-service:
          condition: service_healthy

  carro-service:
    image: carro-service-image:1.0
    ports:
      - 10000:10000
    environment:
      - SPRING_APPLICATION_NAME=carro-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8081
      - SPRING_CLOUD_CONFIG_ENABLED=true
    networks:
      - microservices-network
    depends_on:
       config-server:
          condition: service_healthy
       eureka-server:
          condition: service_healthy
       gateway-service:
          condition: service_healthy

networks:
  microservices-network:
    driver: bridge




